/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyecto1dba.GraphicInterface;


import com.proyecto1dba.AccessData.AcessData;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JPanel;

/**
 *
 * @author Jason
 */
public class PanelReportes extends javax.swing.JPanel {
    
    AcessData AD;
    DateFormat dateF = new SimpleDateFormat("yyyy-MM-dd");
    private static final int CantOrdProd       = 0;
    private static final int MontoVentaDia = 1;
    private static final int MontoVentaDiaProd   = 2;
    private static final int OrdResiCli      = 3;
    /**
     * Creates new form PanelReportes
     */
    public PanelReportes() {
        AD = new AcessData();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel_VentasPorDia = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        jButton_AceptarVerMovimiento = new javax.swing.JButton();
        jLabel78 = new javax.swing.JLabel();
        jButton_CancelarVerMovimiento = new javax.swing.JButton();
        jLabel79 = new javax.swing.JLabel();
        dateChooserCombo_DateReporte = new datechooser.beans.DateChooserCombo();
        jDialog2 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jButton_AceptarVerMovimiento1 = new javax.swing.JButton();
        jButton_CancelarVerMovimiento1 = new javax.swing.JButton();
        jComboBox_tipos = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton_CancelarVerMovimiento2 = new javax.swing.JButton();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        dateChooserCombo_VentProdFech = new datechooser.beans.DateChooserCombo();
        jLabel85 = new javax.swing.JLabel();
        jButton_AceptarVerMovimiento2 = new javax.swing.JButton();
        jLabel86 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton_CancelarVerMovimiento3 = new javax.swing.JButton();
        jLabel87 = new javax.swing.JLabel();
        jButton_AceptarVerMovimiento3 = new javax.swing.JButton();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jComboBox_cantones = new javax.swing.JComboBox<>();
        jDialog_resultados = new javax.swing.JDialog();
        CantOrdCanton = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_canton = new javax.swing.JLabel();
        VentasPordia = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabelMonto = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_dia = new javax.swing.JLabel();
        CantOrdTipoProd = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabelCantidad1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_TipoProd = new javax.swing.JLabel();
        VentasPorProdDia = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabelMonto1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_dia1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelProducto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        label1 = new java.awt.Label();
        jLabel14 = new javax.swing.JLabel();

        jDialog1.setMinimumSize(new java.awt.Dimension(470, 270));
        jDialog1.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        jDialog1.setUndecorated(true);
        jDialog1.getContentPane().setLayout(null);

        jPanel_VentasPorDia.setBackground(new java.awt.Color(153, 153, 153));
        jPanel_VentasPorDia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_VentasPorDia.setMaximumSize(new java.awt.Dimension(500, 300));
        jPanel_VentasPorDia.setMinimumSize(new java.awt.Dimension(500, 300));
        jPanel_VentasPorDia.setPreferredSize(new java.awt.Dimension(500, 300));

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setText("Montos de ventas total por día");
        jLabel77.setMaximumSize(new java.awt.Dimension(467, 22));
        jLabel77.setMinimumSize(new java.awt.Dimension(467, 22));

        jButton_AceptarVerMovimiento.setForeground(new java.awt.Color(0, 51, 51));
        jButton_AceptarVerMovimiento.setText("Aceptar");
        jButton_AceptarVerMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AceptarVerMovimientoActionPerformed(evt);
            }
        });

        jLabel78.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setText("Seleccionar:");

        jButton_CancelarVerMovimiento.setText("Cancelar");
        jButton_CancelarVerMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarVerMovimientoActionPerformed(evt);
            }
        });

        jLabel79.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setText("Día:");

        dateChooserCombo_DateReporte.setCalendarBackground(new java.awt.Color(0, 51, 51));
        dateChooserCombo_DateReporte.setNothingAllowed(false);
        dateChooserCombo_DateReporte.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);

        jPanel_VentasPorDia.setSize(465, 240);

        javax.swing.GroupLayout jPanel_VentasPorDiaLayout = new javax.swing.GroupLayout(jPanel_VentasPorDia);
        jPanel_VentasPorDia.setLayout(jPanel_VentasPorDiaLayout);
        jPanel_VentasPorDiaLayout.setHorizontalGroup(
            jPanel_VentasPorDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VentasPorDiaLayout.createSequentialGroup()
                .addGroup(jPanel_VentasPorDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_VentasPorDiaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_VentasPorDiaLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(dateChooserCombo_DateReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_VentasPorDiaLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jButton_AceptarVerMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jButton_CancelarVerMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_VentasPorDiaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel_VentasPorDiaLayout.setVerticalGroup(
            jPanel_VentasPorDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VentasPorDiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel78)
                .addGap(35, 35, 35)
                .addGroup(jPanel_VentasPorDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserCombo_DateReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel_VentasPorDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_AceptarVerMovimiento)
                    .addComponent(jButton_CancelarVerMovimiento))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jDialog2.setIconImage(null);
        jDialog2.setIconImages(null);
        jDialog2.setMinimumSize(new java.awt.Dimension(500, 270));
        jDialog2.setModal(true);
        jDialog2.setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(489, 233));
        jPanel1.setMinimumSize(new java.awt.Dimension(489, 233));
        jPanel1.setPreferredSize(new java.awt.Dimension(489, 233));

        jLabel80.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("Cantidad de ordenes recibidas por tiopo de producto");
        jLabel80.setMaximumSize(new java.awt.Dimension(467, 22));
        jLabel80.setMinimumSize(new java.awt.Dimension(467, 22));

        jLabel81.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("Seleccionar:");

        jLabel82.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText("Tipo:");

        jButton_AceptarVerMovimiento1.setForeground(new java.awt.Color(0, 51, 51));
        jButton_AceptarVerMovimiento1.setText("Aceptar");
        jButton_AceptarVerMovimiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AceptarVerMovimiento1ActionPerformed(evt);
            }
        });

        jButton_CancelarVerMovimiento1.setText("Cancelar");
        jButton_CancelarVerMovimiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarVerMovimiento1ActionPerformed(evt);
            }
        });

        jComboBox_tipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo1" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addComponent(jButton_AceptarVerMovimiento1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jButton_CancelarVerMovimiento1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_tipos, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel80, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel81)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_tipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_AceptarVerMovimiento1)
                    .addComponent(jButton_CancelarVerMovimiento1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setMaximumSize(new java.awt.Dimension(489, 233));
        jPanel2.setMinimumSize(new java.awt.Dimension(489, 233));

        jButton_CancelarVerMovimiento2.setText("Cancelar");
        jButton_CancelarVerMovimiento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarVerMovimiento2ActionPerformed(evt);
            }
        });

        jLabel83.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setText("Monto de ventas total  por día y por producto");
        jLabel83.setMaximumSize(new java.awt.Dimension(467, 22));
        jLabel83.setMinimumSize(new java.awt.Dimension(467, 22));

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setText("Indicar:");

        dateChooserCombo_VentProdFech.setCalendarBackground(new java.awt.Color(0, 51, 51));
        dateChooserCombo_VentProdFech.setNothingAllowed(false);
        dateChooserCombo_VentProdFech.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);

        jLabel85.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(255, 255, 255));
        jLabel85.setText("Día:");

        jButton_AceptarVerMovimiento2.setForeground(new java.awt.Color(0, 51, 51));
        jButton_AceptarVerMovimiento2.setText("Aceptar");
        jButton_AceptarVerMovimiento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AceptarVerMovimiento2ActionPerformed(evt);
            }
        });

        jLabel86.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 255, 255));
        jLabel86.setText("idProducto:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.proyecto1dba.Images/searchLttBlckBtt.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel83, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel86)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel85)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateChooserCombo_VentProdFech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_AceptarVerMovimiento2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_CancelarVerMovimiento2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel84)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel86, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateChooserCombo_VentProdFech, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_CancelarVerMovimiento2)
                    .addComponent(jButton_AceptarVerMovimiento2))
                .addGap(23, 23, 23))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setMaximumSize(new java.awt.Dimension(489, 233));
        jPanel3.setMinimumSize(new java.awt.Dimension(489, 233));
        jPanel3.setPreferredSize(new java.awt.Dimension(489, 233));

        jButton_CancelarVerMovimiento3.setText("Cancelar");
        jButton_CancelarVerMovimiento3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarVerMovimiento3ActionPerformed(evt);
            }
        });

        jLabel87.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(255, 255, 255));
        jLabel87.setText("Cantidad de órdenes recibidas por lugar de residencia del cliente");
        jLabel87.setMaximumSize(new java.awt.Dimension(467, 22));
        jLabel87.setMinimumSize(new java.awt.Dimension(467, 22));

        jButton_AceptarVerMovimiento3.setForeground(new java.awt.Color(0, 51, 51));
        jButton_AceptarVerMovimiento3.setText("Aceptar");
        jButton_AceptarVerMovimiento3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AceptarVerMovimiento3ActionPerformed(evt);
            }
        });

        jLabel88.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(255, 255, 255));
        jLabel88.setText("Seleccionar:");

        jLabel89.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(255, 255, 255));
        jLabel89.setText("Cantón:");

        jComboBox_cantones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cantón" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jButton_AceptarVerMovimiento3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jButton_CancelarVerMovimiento3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel87, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_cantones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_CancelarVerMovimiento3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel88)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_cantones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(jButton_AceptarVerMovimiento3)))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog2Layout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 4, Short.MAX_VALUE)))
            .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog2Layout.createSequentialGroup()
                    .addGap(0, 13, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 13, Short.MAX_VALUE)))
            .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jDialog_resultados.setIconImage(null);
        jDialog_resultados.setIconImages(null);
        jDialog_resultados.setMinimumSize(new java.awt.Dimension(572, 371));
        jDialog_resultados.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        jDialog_resultados.setUndecorated(true);

        CantOrdCanton.setBackground(new java.awt.Color(255, 255, 255));
        CantOrdCanton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CantOrdCanton.setAlignmentX(0.0F);
        CantOrdCanton.setAlignmentY(0.0F);
        CantOrdCanton.setMaximumSize(new java.awt.Dimension(572, 371));
        CantOrdCanton.setMinimumSize(new java.awt.Dimension(572, 371));
        CantOrdCanton.setPreferredSize(new java.awt.Dimension(572, 371));
        CantOrdCanton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                CantOrdCantonMouseDragged(evt);
            }
        });
        CantOrdCanton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CantOrdCantonMousePressed(evt);
            }
        });

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.proyecto1dba.Images/Cerrar.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Khmer UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Cantidad de órdenes recibidas por lugar de residencia del cliente");

        jLabelCantidad.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCantidad.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelCantidad.setText("cant");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Cantidad:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Cantón:");

        jLabel_canton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel_canton.setAlignmentY(0.0F);

        javax.swing.GroupLayout CantOrdCantonLayout = new javax.swing.GroupLayout(CantOrdCanton);
        CantOrdCanton.setLayout(CantOrdCantonLayout);
        CantOrdCantonLayout.setHorizontalGroup(
            CantOrdCantonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CantOrdCantonLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(CantOrdCantonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CantOrdCantonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_canton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(252, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CantOrdCantonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CantOrdCantonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(CantOrdCantonLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        CantOrdCantonLayout.setVerticalGroup(
            CantOrdCantonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CantOrdCantonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(CantOrdCantonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_canton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CantOrdCantonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        VentasPordia.setBackground(new java.awt.Color(255, 255, 255));
        VentasPordia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        VentasPordia.setAlignmentX(0.0F);
        VentasPordia.setAlignmentY(0.0F);
        VentasPordia.setMaximumSize(new java.awt.Dimension(572, 371));
        VentasPordia.setMinimumSize(new java.awt.Dimension(572, 371));
        VentasPordia.setPreferredSize(new java.awt.Dimension(572, 371));
        VentasPordia.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                VentasPordiaMouseDragged(evt);
            }
        });
        VentasPordia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VentasPordiaMousePressed(evt);
            }
        });

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.proyecto1dba.Images/Cerrar.png"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Khmer UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Montos de ventas total por día");

        jLabelMonto.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMonto.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelMonto.setText("cant");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("Monto:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Día:");

        jLabel_dia.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel_dia.setAlignmentY(0.0F);

        javax.swing.GroupLayout VentasPordiaLayout = new javax.swing.GroupLayout(VentasPordia);
        VentasPordia.setLayout(VentasPordiaLayout);
        VentasPordiaLayout.setHorizontalGroup(
            VentasPordiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentasPordiaLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(VentasPordiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentasPordiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(270, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentasPordiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VentasPordiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(VentasPordiaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        VentasPordiaLayout.setVerticalGroup(
            VentasPordiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentasPordiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(VentasPordiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentasPordiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CantOrdTipoProd.setBackground(new java.awt.Color(255, 255, 255));
        CantOrdTipoProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CantOrdTipoProd.setAlignmentX(0.0F);
        CantOrdTipoProd.setAlignmentY(0.0F);
        CantOrdTipoProd.setMaximumSize(new java.awt.Dimension(572, 371));
        CantOrdTipoProd.setMinimumSize(new java.awt.Dimension(572, 371));
        CantOrdTipoProd.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                CantOrdTipoProdMouseDragged(evt);
            }
        });
        CantOrdTipoProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CantOrdTipoProdMousePressed(evt);
            }
        });

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.proyecto1dba.Images/Cerrar.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Khmer UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Cantidad de órdenes recibidas por tipo de producto.");

        jLabelCantidad1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCantidad1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelCantidad1.setText("cant");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setText("Cantidad:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Tipo:");

        jLabel_TipoProd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel_TipoProd.setAlignmentY(0.0F);

        javax.swing.GroupLayout CantOrdTipoProdLayout = new javax.swing.GroupLayout(CantOrdTipoProd);
        CantOrdTipoProd.setLayout(CantOrdTipoProdLayout);
        CantOrdTipoProdLayout.setHorizontalGroup(
            CantOrdTipoProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CantOrdTipoProdLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(CantOrdTipoProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CantOrdTipoProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_TipoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(252, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CantOrdTipoProdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CantOrdTipoProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(CantOrdTipoProdLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        CantOrdTipoProdLayout.setVerticalGroup(
            CantOrdTipoProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CantOrdTipoProdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(CantOrdTipoProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_TipoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CantOrdTipoProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        VentasPorProdDia.setBackground(new java.awt.Color(255, 255, 255));
        VentasPorProdDia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        VentasPorProdDia.setAlignmentX(0.0F);
        VentasPorProdDia.setAlignmentY(0.0F);
        VentasPorProdDia.setMaximumSize(new java.awt.Dimension(572, 371));
        VentasPorProdDia.setMinimumSize(new java.awt.Dimension(572, 371));
        VentasPorProdDia.setPreferredSize(new java.awt.Dimension(572, 371));
        VentasPorProdDia.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                VentasPorProdDiaMouseDragged(evt);
            }
        });
        VentasPorProdDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VentasPorProdDiaMousePressed(evt);
            }
        });

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.proyecto1dba.Images/Cerrar.png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Khmer UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Monto de ventas total  por día y por producto");

        jLabelMonto1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMonto1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelMonto1.setText("cant");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setText("Monto:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Día:");

        jLabel_dia1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel_dia1.setAlignmentY(0.0F);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("IdProducto:");

        jLabelProducto.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout VentasPorProdDiaLayout = new javax.swing.GroupLayout(VentasPorProdDia);
        VentasPorProdDia.setLayout(VentasPorProdDiaLayout);
        VentasPorProdDiaLayout.setHorizontalGroup(
            VentasPorProdDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentasPorProdDiaLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(VentasPorProdDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(22, 22, 22)
                .addGroup(VentasPorProdDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_dia1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMonto1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(253, 253, 253))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentasPorProdDiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VentasPorProdDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(VentasPorProdDiaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        VentasPorProdDiaLayout.setVerticalGroup(
            VentasPorProdDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentasPorProdDiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(VentasPorProdDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentasPorProdDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_dia1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentasPorProdDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMonto1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog_resultadosLayout = new javax.swing.GroupLayout(jDialog_resultados.getContentPane());
        jDialog_resultados.getContentPane().setLayout(jDialog_resultadosLayout);
        jDialog_resultadosLayout.setHorizontalGroup(
            jDialog_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_resultadosLayout.createSequentialGroup()
                .addGroup(jDialog_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog_resultadosLayout.createSequentialGroup()
                        .addComponent(CantOrdTipoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CantOrdCanton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog_resultadosLayout.createSequentialGroup()
                        .addComponent(VentasPordia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VentasPorProdDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jDialog_resultadosLayout.setVerticalGroup(
            jDialog_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_resultadosLayout.createSequentialGroup()
                .addGroup(jDialog_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CantOrdTipoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantOrdCanton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_resultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VentasPordia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VentasPorProdDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMinimumSize(new java.awt.Dimension(760, 400));
        setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Cantidad de órdenes recibidas por tipo de producto."},
                {"Monto de ventas total por día."},
                {"Monto de ventas total  por día y por producto."},
                {"Cantidad de órdenes recibidas por lugar de residencia del cliente."}
            },
            new String [] {
                "Reporte                                                                                                                                                                                                                                                       "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setMinimumSize(new java.awt.Dimension(15, 287));
        jTable1.setPreferredSize(new java.awt.Dimension(75, 280));
        jTable1.setRowHeight(41);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        label1.setText("Tipo de reporte:");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.proyecto1dba.Images/listBtt.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        int selection = jTable1.getSelectedRow();
        if (selection == CantOrdProd){
            ArrayList<String> tipoPred = AD.getTiposProd();
             this.jComboBox_tipos.removeAllItems();
        for (String tipo : tipoPred) {            
            this.jComboBox_tipos.addItem(tipo);
        }            
            
             showPanelOnDialog2(jPanel1);

        } else if (selection == MontoVentaDia){
            showPanelOnDialog(jPanel_VentasPorDia, jDialog1);
            
        } else if (selection == MontoVentaDiaProd){
            showPanelOnDialog2(jPanel2);             
           
        } else if (selection == OrdResiCli){
          ArrayList<String> cantones = AD.getCantonesClientes();
             this.jComboBox_cantones.removeAllItems();
        for (String canton : cantones) {
           
            this.jComboBox_cantones.addItem(canton);
        }               
            
            showPanelOnDialog2(jPanel3);  
           
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jButton_AceptarVerMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AceptarVerMovimientoActionPerformed
        
        String result =AD.ventaPorDia(dateF.format(dateChooserCombo_DateReporte.getSelectedDate().getTime()));
        jLabel_dia.setText(dateF.format(dateChooserCombo_DateReporte.getSelectedDate().getTime()));
        jLabelMonto.setText(result);
        jDialog1.setVisible(false);
        showResult(2);
    }//GEN-LAST:event_jButton_AceptarVerMovimientoActionPerformed

    private void jButton_CancelarVerMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarVerMovimientoActionPerformed
        jDialog1.remove(jPanel_VentasPorDia);
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton_CancelarVerMovimientoActionPerformed

    private void jButton_AceptarVerMovimiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AceptarVerMovimiento1ActionPerformed
 
        String result = AD.getCantOrdTipoProd((jComboBox_tipos.
                getSelectedIndex()+1)+"");
         jDialog2.setVisible(false);
         jLabel_TipoProd.setText(jComboBox_tipos.getSelectedItem().toString());
         jLabelCantidad1.setText(result);
         showResult(1);
         
        
        
        
        
    }//GEN-LAST:event_jButton_AceptarVerMovimiento1ActionPerformed

    private void jButton_CancelarVerMovimiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarVerMovimiento1ActionPerformed
        jDialog2.setVisible(false);
    }//GEN-LAST:event_jButton_CancelarVerMovimiento1ActionPerformed

    private void jButton_CancelarVerMovimiento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarVerMovimiento2ActionPerformed
        closejDialog(jDialog2);
    }//GEN-LAST:event_jButton_CancelarVerMovimiento2ActionPerformed

    private void jButton_CancelarVerMovimiento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarVerMovimiento3ActionPerformed
       jDialog2.setVisible(false);
    }//GEN-LAST:event_jButton_CancelarVerMovimiento3ActionPerformed

    private void jButton_AceptarVerMovimiento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AceptarVerMovimiento2ActionPerformed
      String monto = AD.ventasProdDias(dateF.format(dateChooserCombo_VentProdFech.
      getSelectedDate().getTime()),jTextField1.getText());
      jLabel_dia1.setText(dateF.format(dateChooserCombo_VentProdFech.
      getSelectedDate().getTime()));
      jLabelProducto.setText(jTextField1.getText());
      jLabelMonto1.setText(monto);
      if (monto == "null"){
          jLabelMonto1.setText("0");
      }
      
      jDialog2.setVisible(false);
      showResult(3);
      
    }//GEN-LAST:event_jButton_AceptarVerMovimiento2ActionPerformed

    private void jButton_AceptarVerMovimiento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AceptarVerMovimiento3ActionPerformed
        String result = AD.getOrdenesCanton((jComboBox_cantones.getSelectedIndex()+1)+"");
        jLabel_canton.setText(jComboBox_cantones.getSelectedItem().toString());
        jLabelCantidad.setText(result);
        jDialog2.setVisible(false);
        showResult(4);
        
        
    }//GEN-LAST:event_jButton_AceptarVerMovimiento3ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        jDialog_resultados.setVisible(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void CantOrdCantonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CantOrdCantonMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_CantOrdCantonMouseDragged

    private void CantOrdCantonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CantOrdCantonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantOrdCantonMousePressed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        jDialog_resultados.setVisible(false);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void VentasPordiaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentasPordiaMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_VentasPordiaMouseDragged

    private void VentasPordiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentasPordiaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_VentasPordiaMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         NewJDialog_Buscador buscador = new NewJDialog_Buscador();
         buscador.actualizaTablaParaInventario();

         String id = buscador.getIdProducto();
         if(id==null){
            return;
         }
         jTextField1.setText(id);
        
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
         jDialog_resultados.setVisible(false);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void VentasPorProdDiaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentasPorProdDiaMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_VentasPorProdDiaMouseDragged

    private void VentasPorProdDiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentasPorProdDiaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_VentasPorProdDiaMousePressed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
         jDialog_resultados.setVisible(false);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void CantOrdTipoProdMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CantOrdTipoProdMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_CantOrdTipoProdMouseDragged

    private void CantOrdTipoProdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CantOrdTipoProdMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantOrdTipoProdMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CantOrdCanton;
    private javax.swing.JPanel CantOrdTipoProd;
    private javax.swing.JPanel VentasPorProdDia;
    private javax.swing.JPanel VentasPordia;
    private datechooser.beans.DateChooserCombo dateChooserCombo_DateReporte;
    private datechooser.beans.DateChooserCombo dateChooserCombo_VentProdFech;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton_AceptarVerMovimiento;
    private javax.swing.JButton jButton_AceptarVerMovimiento1;
    private javax.swing.JButton jButton_AceptarVerMovimiento2;
    private javax.swing.JButton jButton_AceptarVerMovimiento3;
    private javax.swing.JButton jButton_CancelarVerMovimiento;
    private javax.swing.JButton jButton_CancelarVerMovimiento1;
    private javax.swing.JButton jButton_CancelarVerMovimiento2;
    private javax.swing.JButton jButton_CancelarVerMovimiento3;
    private javax.swing.JComboBox<String> jComboBox_cantones;
    private javax.swing.JComboBox<String> jComboBox_tipos;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog_resultados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCantidad1;
    private javax.swing.JLabel jLabelMonto;
    private javax.swing.JLabel jLabelMonto1;
    private javax.swing.JLabel jLabelProducto;
    private javax.swing.JLabel jLabel_TipoProd;
    private javax.swing.JLabel jLabel_canton;
    private javax.swing.JLabel jLabel_dia;
    private javax.swing.JLabel jLabel_dia1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_VentasPorDia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables

    private void showPanelOnDialog(JPanel pPanel, JDialog pDialog) {
        pDialog.setSize(pPanel.getSize());
        pPanel.setLocation(0, 0);
        pDialog.setLocationRelativeTo(null);
        pDialog.add(pPanel);
        pPanel.setVisible(true);
        pDialog.setVisible(true);
        
    }

    private void showPanelOnDialog2(JPanel panel) {
        jDialog2.setLocationRelativeTo(null);
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);   
        jPanel3.setVisible(false);
        panel.setVisible(true);
        jDialog2.setVisible(true);
    }

    private void closejDialog(JDialog jD) {
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);   
        jPanel3.setVisible(false); 
        jD.setVisible(false);

        
    }

    private void showResult(int numReporte) {
        CantOrdCanton.setVisible(false);
        VentasPordia.setVisible(false);
        VentasPorProdDia.setVisible(false);
        CantOrdTipoProd.setVisible(false);
        
        if(numReporte == 1){
            jDialog_resultados.setLocationRelativeTo(null);
            CantOrdTipoProd.setLocation(0, 0);
            CantOrdTipoProd.setVisible(true);
            jDialog_resultados.setVisible(true);
            
        }
        else if( numReporte==2){
            jDialog_resultados.setLocationRelativeTo(null);
            VentasPordia.setLocation(0, 0);
            VentasPordia.setVisible(true);
            jDialog_resultados.setVisible(true);
            
        }
         else if( numReporte==3){
            jDialog_resultados.setLocationRelativeTo(null);
            VentasPorProdDia.setLocation(0, 0);
            VentasPorProdDia.setVisible(true);
            jDialog_resultados.setVisible(true);
            
        }
        else if( numReporte==4){
            jDialog_resultados.setLocationRelativeTo(null);
            CantOrdCanton.setLocation(0, 0);
            CantOrdCanton.setVisible(true);
            jDialog_resultados.setVisible(true);
            
        }
        
    }
}
